Distance
TomFanella4/meetover pull request #40
Opened 2018-04-06 00:56 UTC by raokrutarth

2018-04-06 04:07 UTC, mpace965 approved these changes
Looks good to me, tested on my machine

2018-04-06 04:51 UTC, mpace965 requested changes
The dataset needs to be put in and accessed from static storage.

2018-04-06 05:03 UTC, TomFanella4 requested changes
Can we put the changes to the dataset on hold? Making the large files even larger is going to make pruning take longer.

2018-04-06 18:01 UTC, TomFanella4 approved these changes

2018-04-06 18:13 UTC, raokrutarth commented
@mpace965 is static storage google drive? I believe I'm writing the generation code as if we use the files directly from disk and Tom will transition that code to the cloud file access and clean up any large files in data/

2018-04-08 00:03 UTC, mpace965 approved these changes
I had a couple of questions, but otherwise looks good for now.

2018-04-08 00:03 UTC, mpace965 commented on backend/Handlers.go
> +		}
`seedUser` can be removed in its entirety

2018-04-08 00:03 UTC, mpace965 commented on backend/data/model.go
> +// }
What is the purpose of this file?

2018-04-08 04:26 UTC, mpace965 requested changes
This branch does not currently build. I get this when running `go build`:

```
# meetover/backend
./Handlers.go:90:37: undefined: cachedUsers
./Handlers.go:92:21: undefined: cachedUsers
./Handlers.go:110:35: unknown field 'Long' in struct literal of type Geolocation
./Handlers.go:110:50: unknown field 'Lat' in struct literal of type Geolocation
./Location.go:37:25: center.Lat undefined (type Geolocation has no field or method Lat)
./Location.go:37:37: center.Long undefined (type Geolocation has no field or method Long)
./Location.go:37:49: point.Lat undefined (type Geolocation has no field or method Lat)
./Location.go:37:60: point.Long undefined (type Geolocation has no field or method Long)
./UserManagement.go:252:2: undefined: cachedUsers
```

2018-04-08 17:29 UTC, raokrutarth commented
My bad on the build issue. Was not aware of the geoloc field name change.

2018-04-08 17:55 UTC, TomFanella4 requested changes
Branch now builds. Left several comments that need to be addressed before merged.

2018-04-08 17:55 UTC, TomFanella4 commented on backend/UserManagement.go
> +var cachedUsers []User
Why do we still need `cachedUsers`? I thought we decided we would get all users from Firebase?

2018-04-08 17:55 UTC, TomFanella4 commented on backend/UserManagement.go
> +func LoadTestUsers() {
Related to `cachedUsers` comment.

2018-04-08 17:55 UTC, TomFanella4 commented on backend/main.go
> +	// LoadTestUsers()
Related to `cachedUsers` comment.

2018-04-08 17:55 UTC, TomFanella4 commented on backend/Handlers.go
> +	} else if tt == "seedUser" {
Related to `cachedUsers` comment.

2018-04-08 17:55 UTC, TomFanella4 commented on backend/Location.go
> +func makeTimestamp() int64 {
`makeTimestamp()` can be removed because the timestamp is created on the client.

2018-04-08 17:55 UTC, TomFanella4 commented on backend/data/model.go
> +// }
I'm also confused as to why we need this file.

2018-04-09 00:25 UTC, TomFanella4 approved these changes

2018-04-09 00:27 UTC, merged